# -*- coding: utf-8 -*-
"""blc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17YHUEZdMFhbGwoN5M6O7Hge_SkdViT7D

# Build a Blockchain
"""

!pip install ipyparallel

#Import statements
import hashlib as hasher 
import random as rand
import time 
import datetime as date
import ipyparallel as ipp
import numpy as np
import matplotlib.pyplot as plt

"""# Blockchain Data Structure Design"""

class Block:
    def __init__(self, index, timestamp, data, previous_hash, nonce=0):
        self.index = index
        self.timestamp = timestamp
        self.data = data
        self.nonce = nonce #set to zero as default not applicable in first section 
        self.previous_hash = previous_hash
        self.hash = self.hash_block()

    def hash_block(self):
      hash_object = hasher.sha256()

      # Update the hash object with input data
      input_data = ''.join([str(self.index), str(self.timestamp), str(self.data), str(self.previous_hash),str(self.nonce)])
      hash_object.update(input_data.encode('utf-8'))

      # Get the hexadecimal representation of the hash digest
      hash_digest = hash_object.hexdigest()

      return hash_digest

#Creates the first block with current time and generic data
def create_genesis_block():
    # Manually construct a block with
    # index zero and arbitrary previous hash
    return Block(0, date.datetime.now(), "Genesis Block", "0")

#Function that creates the next block, given the last block on the chain you want to mine on

def next_block(last_block, nonce=0):
   
   
    nindex= last_block.index+1
    # print("Hey! I'm block %d" % nindex)
    return Block(nindex, date.datetime.now(), "Hey! I'm block %d" %nindex, last_block.hash)

"""# Proof of Work Simulation"""

import time

def generate_nonce(length=20):
    return ''.join([str(rand.randint(0, 9)) for i in range(length)])

def generate_difficulty_bound(difficulty=1):
    diff_str = ""
    for i in range(difficulty):
        diff_str += '0'
    for i in range(64 - difficulty):
        diff_str += 'F'
    diff_str = "0x" + diff_str  # "0x" needs to be added at the front to specify that it is a hex representation
    return(int(diff_str, 16))  # Specifies that we want to create an integer of base 16 (as opposed to the default base 10)

#Given a previous block and a difficulty metric, finds a nonce that results in a lower hash value
def find_next_block(last_block, difficulty, nonce_length):
    difficulty_bound = generate_difficulty_bound(difficulty)
    start = time.process_time() 
    new_block = next_block(last_block)
    hashes_tried = 1 
    
    while int(new_block.hash, 16)> difficulty_bound:
         nonce= generate_nonce(nonce_length)
         new_block = next_block(last_block, nonce)


     
    time_taken = time.process_time() - start
    return(time_taken, hashes_tried, new_block)

"""### Create Proof of Work Blockchain """

# Create the blockchain and add the genesis block
blockchain_pow = [create_genesis_block()]

#Create our initial reference to previous block which points to the genesis block
previous_block = blockchain_pow[0]

# How many blocks should we add to the chain after genesis block
num_blocks = 20

#magnitude of difficulty of hash - number of zeroes that must be in the beginning of the hash
difficulty = 3

#length of nonce that will be generated and added
nonce_length = 20

# Add blocks to the chain based on difficulty with nonces of length nonce_length
def create_pow_blockchain(num_blocks, difficulty, blockchain_pow, previous_block, nonce_length, print_data=1):
    hash_array = []
    time_array = []
    for i in range(0, num_blocks):
        time_taken, hashes_tried, block_to_add = find_next_block(previous_block, difficulty, nonce_length)
        blockchain_pow.append(block_to_add)
        previous_block = block_to_add
        hash_array.append(hashes_tried)
        time_array.append(time_taken)
        # Tell everyone about it!
        if print_data:
            print("Block #{} has been added to the blockchain!".format(block_to_add.index))
            print("{} Hashes Tried!".format(hashes_tried))
            print("Time taken to find block: {}".format(time_taken))
            print("Hash: {}\n".format(block_to_add.hash))
    return(hash_array, time_array)

hash_array, time_array = create_pow_blockchain(num_blocks, difficulty, blockchain_pow, previous_block, nonce_length)